# BLOGPOST MANAGEMENT

GET {{host-url}}/blogPost/all

###

GET {{host-url}}/blogPost/1

###

GET {{host-url}}/blogPost/allByUser/Von

###

GET {{host-url}}/blogPost/allByUser/Moe

###

GET {{host-url}}/blogPost/allByTag/?tag=Money

###

GET {{host-url}}/blogPost/allByDate/?year=2020&month=4&day=15

###

POST {{host-url}}/blogPost/save
Content-Type: application/json

{
  "blogId": null,
  "dateCreated": "2020-01-01",
  "username": "Von",
  "title": "testTitle",
  "body": "testBody",
  "tag": "test",
  "status": "posted",
  "userAccount": {
    "userId": 3,
    "dateCreated": "2015-04-09",
    "username": "Von",
    "password": "vonPass",
    "email": "von@gmail.com"
  }
}

###

PUT {{host-url}}/blogPost/update/1
Content-Type: application/json

{
  "title": "testTitle",
  "body": "testBody",
  "tag": "test",
  "status": "posted"
}

###

DELETE {{host-url}}/blogPost/delete/2

###

DELETE {{host-url}}/blogPost/deleteAll

###





# COMMENT MANAGEMENT

GET {{host-url}}/comment/all

###

GET {{host-url}}/comment/allByUserId/4

###

GET {{host-url}}/comment/allByBlogId/1

###

GET {{host-url}}/comment/1

###

GET {{host-url}}/comment/+likes/1

###

POST {{host-url}}/comment/save
Content-Type: application/json

{
  "dateCreated": "2015-04-09",
  "username": "Rosalind",
  "text": "I admire your writing sir.",
  "likes": 100,
  "blogId": 2,
  "userId": 3
}

###

PUT {{host-url}}/comment/update/1?newText=I admire your change sir.

###

DELETE {{host-url}}/comment/delete/1

###




# USER MANAGEMENT

GET {{host-url}}/userAccount/all

###

GET {{host-url}}/userAccount/3

###

GET {{host-url}}/userAccount/login?username=Von&password=vonPass

###

POST {{host-url}}/userAccount/save
Content-Type: application/json

{
  "dateCreated": "2015-04-09",
  "username": "test",
  "password": "testPass",
  "email": "test@gmail.com"
}

###

PUT {{host-url}}/userAccount/update/1
Content-Type: application/json

{
  "title": "testTitle",
  "username": "bento",
  "password": "testPassBento",
  "email": "bento@gmail.com"
}

###

DELETE {{host-url}}/userAccount/delete/5

###